src/Otus.Teaching.PromoCodeFactor.MVC/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Otus.Teaching.PromoCodeFactor.MVC.Models;
using Otus.Teaching.PromoCodeFactory.Core.Domain.PromoCodeManagement;
using Otus.Teaching.PromoCodeFactory.Core.Interfaces.Repositories;
using Otus.Teaching.PromoCodeFactory.DataAccess;

namespace Otus.Teaching.PromoCodeFactor.MVC
{
    public class CustomersController : Controller
    {
        private readonly IRepository<Customer> _customerRepository;
        private readonly IRepository<Preference> _preferenceRepository;

        public CustomersController(IRepository<Preference> preferenceRepository,
            IRepository<Customer> customerRepository)
        {
            _preferenceRepository = preferenceRepository;
            _customerRepository = customerRepository;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            IEnumerable<Customer> customers;
            try
            {
                customers = await _customerRepository.GetAllAsync();
                if (customers == null) new List<Customer>();
            }
            catch (Exception)
            {
                customers = new List<Customer>();
            }

            var response = customers.Select(x => new CustomerViewModel(x)).ToList();

            return View(response);
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _customerRepository.GetByIdAsync(id.Value);

            if (customer == null)
            {
                return NotFound();
            }

            var response = new CustomerFullViewModel(customer);
            return View(response);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CustomerViewModel request)
        {
            if (!ModelState.IsValid) return View(request);

            var customer = new Customer()
            {
                Email = request.Email,
                FirstName = request.FirstName,
                LastName = request.LastName
            };

            await _customerRepository.AddAsync(customer);

            return RedirectToAction(nameof(Index));
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _customerRepository.GetByIdAsync(id.Value);

            if (customer == null)
            {
                return NotFound();
            }

            return View(new CustomerViewModel(customer));
        }

        // POST: Customers/Edit/5       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CustomerViewModel request)
        {
            if (!ModelState.IsValid) return View(request);

            var customer = await _customerRepository.GetByIdAsync(request.Id);

            if (customer == null)
                return NotFound();

            customer.Email = request.Email;
            customer.FirstName = request.FirstName;
            customer.LastName = request.LastName;


            await _customerRepository.UpdateAsync(customer);


            return RedirectToAction(nameof(Index));
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _customerRepository.GetByIdAsync(id.Value);

            if (customer == null)
            {
                return NotFound();
            }

            return View(new CustomerViewModel(customer));
        }


        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var customer = await _customerRepository.GetByIdAsync(id);

            if (customer == null)
                return NotFound();

            await _customerRepository.DeleteAsync(customer);

            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(Guid id)
        {
            var customer = _customerRepository.GetByIdAsync(id).Result;

            return (customer != null);
        }
    }
}

src/Otus.Teaching.PromoCodeFactor.MVC/Controllers/PreferencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Otus.Teaching.PromoCodeFactor.MVC.Models;
using Otus.Teaching.PromoCodeFactory.Core.Domain.PromoCodeManagement;
using Otus.Teaching.PromoCodeFactory.Core.Interfaces.Repositories;
using Otus.Teaching.PromoCodeFactory.DataAccess;

namespace Otus.Teaching.PromoCodeFactor.MVC.Controllers
{
    public class PreferencesController : Controller
    {
        private readonly IRepository<Preference> _preferencesRepository;

        public PreferencesController(IRepository<Preference> preferencesRepository)
        {
            _preferencesRepository = preferencesRepository;
        }

        // GET: Preferences
        public async Task<IActionResult> Index()
        {
            IEnumerable<Preference> preferences;
            try
            {
                preferences = await _preferencesRepository.GetAllAsync();
                if (preferences == null) new List<Preference>();
            }
            catch (Exception)
            {
                preferences = new List<Preference>();
            }

            var response = preferences.Select(x => new PreferenceViewModel(x)).ToList();

            return View(response);
        }

        // GET: Preferences/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var preference = await _preferencesRepository.GetByIdAsync(id.Value);

            if (preference == null)
            {
                return NotFound();
            }

            var response = new PreferenceViewModel(preference);
            return View(response);
        }

        // GET: Preferences/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Preferences/Create       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PreferenceViewModel request)
        {
            if (!ModelState.IsValid) return View(request);

            var preference = new Preference()
            {
                Name = request.Name
            };

            await _preferencesRepository.AddAsync(preference);

            return RedirectToAction(nameof(Index));
        }

        // GET: Preferences/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var preference = await _preferencesRepository.GetByIdAsync(id.Value);

            if (preference == null)
            {
                return NotFound();
            }

            return View(new PreferenceViewModel(preference));
        }

        // POST: Preferences/Edit/5       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PreferenceViewModel request)
        {
            if (!ModelState.IsValid) return View(request);

            var preference = await _preferencesRepository.GetByIdAsync(request.Id);

            if (preference == null)
                return NotFound();

            preference.Name = request.Name;

            await _preferencesRepository.UpdateAsync(preference);

            return RedirectToAction(nameof(Index));
        }

        // GET: Preferences/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var preference = await _preferencesRepository.GetByIdAsync(id.Value);

            if (preference == null)
            {
                return NotFound();
            }

            return View(new PreferenceViewModel(preference));
        }

        // POST: Preferences/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var preference = await _preferencesRepository.GetByIdAsync(id);

            if (preference == null)
                return NotFound();

            await _preferencesRepository.DeleteAsync(preference);

            return RedirectToAction(nameof(Index));
        }

        private bool PreferenceExists(Guid id)
        {
            var preference = _preferencesRepository.GetByIdAsync(id).Result;

            return (preference != null);
        }
    }
}

src/Otus.Teaching.PromoCodeFactor.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="author" content='svs'/>
    <link rel="icon" href="~/favicon.ico"/>

    <title>@ViewData["Title"] - @ViewData["ActionTitle"] </title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/dashboard.css"/>


    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet"/>
</head>
<body>
    <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
        <a class="navbar-brand col-sm-3 col-md-2 ml-1" href="/">На главную</a>

        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Preferences" asp-action="Index">
                        <span data-feather="file"></span>
                        Предпочтения
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="Index">
                        <span data-feather="users"></span>
                        Пользователи
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Promocodes" asp-action="Index">
                        <span data-feather="layers"></span>
                        Промокоды
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
                    <h1 class="h2">@ViewData["ActionTitle"]</h1>
                </div>

                @RenderBody()

            </main>
        </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->

    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../dist/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>feather.replace()</script>
    @RenderSection("Scripts", required: false)
</body>
</html>